
// Objective-C API for talking to the following Go packages
//
//	github.com/syllabix/ecaas
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ecaas_FRAMEWORK_H__
#define __Ecaas_FRAMEWORK_H__

#include "Ecaas.objc.h"
#include "Universe.objc.h"

#endif
